services:
  notiffio:
    container_name: notiffio
    hostname: notiffio
    image: ghcr.io/deadcxap/bee-notiffio:1.0
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
